export const actionType = {
  GET_ALL_GATEWAYS: 'GET_ALL_GATEWAYS',
  GET_GATEWAY_DETAILS: 'GET_GATEWAY_DETAILS',
  ADD_GATEWAY: 'ADD_GATEWAY',
  EDIT_GATEWAY: 'EDIT_GATEWAY',
  DELETE_GATEWAY: 'DELETE_GATEWAY',

  GET_ALL_DEVICES: 'GET_ALL_DEVICES',
  GET_ALL_DEVICES_COUNT: 'GET_ALL_DEVICES_COUNT',
  GET_DEVICE_DETAILS: 'GET_DEVICE_DETAILS',
  ADD_DEVICE: 'ADD_DEVICE',
  EDIT_DEVICE: 'EDIT_DEVICE',
  DELETE_DEVICE: 'DELETE_DEVICE',
  
}
